### ISSUE TITLE
국제화(언어) 설정

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk-landing#4]
## Todo

- [x] 언어 설정 select box 컴포넌트 작성
- [x] select box의 값에 따라 모든 뷰에 대해서 텍스트가 변경되도록 설정 
- [x] 언어 별 텍스트 정리 컨벤션 고안
- [x] 유저의 이용 언어를 이용해 default language 설정 가능 여부 조사

**Comment by HyunmoAhn** [comment]
> 유저의 이용 언어를 이용해 default language 설정 가능 여부 조사

관련하여 `window.navigator.language` 값을 통해서 판별 가능

`ko-KR`, `ko`는 한국어
`en-US`, `en`는 영어

`ko-KR`, `ko`를 제외한 language의 초깃값은 English로 설정

**Comment by HyunmoAhn** [comment]
[I18N(국제화) 관리 컨벤션](https://github.com/AhKi/oh-my-desk-landing/wiki/I18N-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EA%B4%80%EB%A6%AC-%EC%BB%A8%EB%B2%A4%EC%85%98) 위키 참조 바랍니다.
